package view;


import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jonas Zacari
 */
public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form ParkingLot
     */
    public LoginView() {
        initComponents();
        this.setLocationRelativeTo(null); // Centralizar a tela.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmial = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        emailUsu = new javax.swing.JTextField();
        senhaUsu = new javax.swing.JPasswordField();
        Entrar = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        avisoEmail = new javax.swing.JLabel();
        avisoSenha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblEmial.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblEmial.setText("E-Mail");

        lblSenha.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSenha.setText("Senha");

        emailUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailUsuActionPerformed(evt);
            }
        });

        senhaUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaUsuActionPerformed(evt);
            }
        });

        Entrar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Entrar.setText("Entrar");
        Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarActionPerformed(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        titulo.setText("ConcessionariaFast");

        avisoEmail.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        avisoEmail.setForeground(new java.awt.Color(255, 51, 153));

        avisoSenha.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        avisoSenha.setForeground(new java.awt.Color(255, 51, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(senhaUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmial)
                            .addComponent(lblSenha))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(titulo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(emailUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avisoEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(avisoSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(titulo)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avisoEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEmial)
                        .addComponent(emailUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avisoSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSenha)
                        .addComponent(senhaUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addComponent(Entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailUsuActionPerformed

    private void EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarActionPerformed
     
    }//GEN-LAST:event_EntrarActionPerformed

    private void senhaUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaUsuActionPerformed

    public String getEmailUsu() {
        return emailUsu.getText();
    }

    public void setEmailUsu(JTextField emailUsu) {
        this.emailUsu = emailUsu;
    }

    public String getSenhaUsu() {
        return senhaUsu.getText();
    }

    public void setSenhaUsu(JPasswordField senhaUsu) {
        this.senhaUsu = senhaUsu;
    }

    public JButton getEntrar() {
        return Entrar;
    }

    public JLabel getAvisoEmail() {
        return avisoEmail;
    }

    public void setAvisoEmail(String avisoEmail) {
        this.avisoEmail.setText(avisoEmail);
    }

    public JLabel getAvisoSenha() {
        return avisoSenha;
    }

    public void setAvisoSenha(String avisoSenha) {
        this.avisoSenha.setText(avisoSenha);
    }

    public JLabel getLblEmial() {
        return lblEmial;
    }

    public void setLblEmial(JLabel lblEmial) {
        this.lblEmial = lblEmial;
    }

    public JLabel getLblSenha() {
        return lblSenha;
    }

    public void setLblSenha(JLabel lblSenha) {
        this.lblSenha = lblSenha;
    }
    
    public void setEntrar(JButton Entrar) {
        this.Entrar = Entrar;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Entrar;
    private javax.swing.JLabel avisoEmail;
    private javax.swing.JLabel avisoSenha;
    private javax.swing.JTextField emailUsu;
    private javax.swing.JLabel lblEmial;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JPasswordField senhaUsu;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
